### PR TITLE
Fix for device not enabled in settings

### PR DESCRIPTION
**Pull request by im85288**
Although the variables with the device.xml are not populated correctly, this fix still resolves the non enabled setting of the device in plex settings

### CODE REVIEW

**Comment by jkaberg** [comment]
Thanks!

**Comment by nmcrae85** [comment]
Is this issue resolved now? I still see the error "Device not found. Ensure your device is powered on and connected to your network. #21

**Comment by irishj** [comment]
Works fine for me now.  Even updated to the latest plex pass server version and the tuner is still showing

**Comment by nmcrae85** [comment]
Reboot of plex sorted this. 

Only issue I see is with recording. On the end of a program schedule the DVR continues to record and not end the process. No sure if that's known bug or expected behaviour. Using Auto IPTV in my setup

**Pull request merged**
